language: node_js
node_js: lts/*
stages:
- lint
- deploy
jobs:
  include:
  - stage: lint
    name: Lint JS
    script: npm run lint:js
  - script: npm run lint:ec
    name: Lint editorconfig
  - stage: deploy
    name: Deploy
    script: npm run build
    before_deploy:
      - openssl aes-256-cbc -K $encrypted_f65e690cb8c7_key -iv $encrypted_f65e690cb8c7_iv
        -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
    deploy:
      provider: script
      script: ".travis/deploy.sh"
      skip_cleanup: true
      on:
        branch: master
