language: node_js
node_js: stable
stages:
- lint
- deploy
jobs:
  include:
  - stage: lint
    name: Lint JS
    script: npm run lint:js
  - script: npm run lint:ec
    name: Lint editorconfig
  - stage: deploy
    name: Deploy
    script: npm run build
    deploy:
      provider: script
      script: ".travis/deploy.sh"
      skip_cleanup: true
      on:
        branch: master
